/* Paginas principales */
export * from "./Empleados"
export * from "./AjusteInventario"
export * from "./Categorias"
export * from "./Clientes"
export * from "./Compras"
export * from "./Error"
export * from "./Inicio"
export * from "./Marcas"
export * from "./Productos"
export * from "./Proveedores"
export * from "./Reportes"
export * from "./Ventas"
export * from "./Usuarios"
export * from "./Sucursales"
export * from "./Roles"

/* Formularios para crear nuevo registro */
export * from "./Formularios/FormMarcas"
export * from "./Formularios/FormProveedores"
export * from "./Formularios/FormAjusteInventario"
export * from "./Formularios/FormCategorias"
export * from "./Formularios/FormClientes"
export * from "./Formularios/FormCompras"
export * from "./Formularios/FormEmpleados"
export * from "./Formularios/FormProductos"
export * from "./Formularios/FormUsuario"
export * from "./Formularios/FormVentas"
export * from "./Formularios/FormSucursal"
export * from "./Formularios/FormRoles"

/* Formularios para editar registros */
export * from "./FormulariosUpdate/EditarMarcas"
export * from "./FormulariosUpdate/EditarProveedores"
export * from "./FormulariosUpdate/EditarCategorias"
export * from "./FormulariosUpdate/EditarClientes"
export * from "./FormulariosUpdate/EditarEmpleados"
export * from "./FormulariosUpdate/EditarProductos"
export * from "./FormulariosUpdate/EditarUsuario"
export * from "./FormulariosUpdate/EditarSucursal"
export * from "./FormulariosUpdate/EditarRol"

